import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

PIXELFED_ACCESS_TOKEN = os.getenv("PIXELFED_ACCESS_TOKEN")
PIXELFED_USERNAME = os.getenv("PIXELFED_USERNAME")
PIXELFED_INSTANCE = os.getenv("PIXELFED_INSTANCE")
PIXELFED_API_URL = f"https://{PIXELFED_INSTANCE}/api/v1"

INSTAGRAM_ACCESS_TOKEN = os.getenv("INSTAGRAM_ACCESS_TOKEN")
INSTAGRAM_PAGE_ID = os.getenv("INSTAGRAM_PAGE_ID")
INSTAGRAM_GRAPH_API_URL = f"https://graph.facebook.com/v21.0/{INSTAGRAM_PAGE_ID}/media"

YOURLS_API_URL = os.getenv("YOURLS_API_URL")
YOURLS_API_SIGNATURE = os.getenv("YOURLS_API_SIGNATURE")

POSTED_LOG_FILE = "posted.logs.json"

MASTODON_ACCESS_TOKEN = os.getenv("MASTODON_ACCESS_TOKEN")
MASTODON_USERNAME = os.getenv("MASTODON_USERNAME")
MASTODON_INSTANCE = os.getenv("MASTODON_INSTANCE")
MASTODON_API_URL = f"https://{MASTODON_INSTANCE}/api/v1"

TWITTER_API_KEY = os.getenv("TWITTER_API_KEY")
TWITTER_API_SECRET = os.getenv("TWITTER_API_SECRET")
TWITTER_ACCESS_TOKEN = os.getenv("TWITTER_ACCESS_TOKEN")
TWITTER_ACCESS_TOKEN_SECRET = os.getenv("TWITTER_ACCESS_TOKEN_SECRET")
